#!/usr/bin/env bash

# Hooks are sourced, so we need to set flags via `set`, not shebang.
set -eu

OPTIONS="--verbose --depth=1"

export BUILDKITE_GIT_CLONE_FLAGS="$OPTIONS"
export BUILDKITE_GIT_FETCH_FLAGS="$OPTIONS"
