#!/usr/bin/env bash

# Hooks are sourced, so we need to set flags via `set`, not shebang.
set -eu

OPTIONS="--verbose --depth=1"

# --depth does not affect submodules when cloning; from the manpage:
# If you want to clone submodules shallowly, also pass --shallow-submodules.
export BUILDKITE_GIT_CLONE_FLAGS="$OPTIONS --shallow-submodules"
export BUILDKITE_GIT_FETCH_FLAGS="$OPTIONS"
